<a href="https://colab.research.google.com/github/masrik-dev/Deep-Learning-with-TensorFlow-and-Python/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try

# Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number or dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) #specify the data type with dtype parameter.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# What's the number dimensions of another)matrix?
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


# Creating tensors with tf.Variable

In [12]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of the elements in our chagneable tensor
#changeable_tensor[0] = 7
#changeable_tensor

In [14]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try change our unchangeable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [16]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [17]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
# Shuffle our not_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Exercise: Generate random tensor, and shuffle it. Then test the global and local seed code.

In [20]:
# Step 1: Create random tensor:
random_tensor = tf.random.Generator.from_seed(32)
random_tensor = random_tensor.normal(shape=(5, 4))
random_tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.2364518 ],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265],
       [-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
       [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
       [-0.645002  ,  0.18022095, -0.14656258,  0.34374258]],
      dtype=float32)>

In [21]:
random_tensor.ndim

2

In [22]:
# Step 2: Shuffle the random_tensor.
shuffle_tensor = tf.random.shuffle(random_tensor)
shuffle_tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265],
       [ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.2364518 ],
       [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
       [-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174]],
      dtype=float32)>

In [23]:
tensor = tf.constant(shuffle_tensor)
tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265],
       [ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.2364518 ],
       [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
       [-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174]],
      dtype=float32)>

### If neither the global seed nor the operation seed is set:

In [24]:
# we get different results for every call to the random op and every re-run of the program:

print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform(tensor.shape))  # generates 'A2'

tf.Tensor([0.46878946], shape=(1,), dtype=float32)
tf.Tensor(
[[0.80980325 0.40774596 0.6347301  0.03373289]
 [0.3255782  0.8647258  0.11275935 0.7356818 ]
 [0.05561268 0.27911854 0.9791113  0.8301457 ]
 [0.09772968 0.93329287 0.40442216 0.72531164]
 [0.1995914  0.31302822 0.9068091  0.37591422]], shape=(5, 4), dtype=float32)


### If the global seed is set but the operation seed is not set:


In [25]:
# we get different results for every call to the random op, but the same sequence for every re-run of the program:

tf.random.set_seed(64)
print(tf.random.uniform([3]))             # generates 'A1'
print(tf.random.uniform(tensor.shape))    # generates 'A2'


tf.Tensor([0.41049755 0.47658968 0.46416903], shape=(3,), dtype=float32)
tf.Tensor(
[[0.04468966 0.6561477  0.33908975 0.823082  ]
 [0.3915465  0.05389285 0.9497212  0.7511488 ]
 [0.29618108 0.11224461 0.5920911  0.6658716 ]
 [0.72812736 0.5153334  0.7647536  0.57969654]
 [0.740461   0.86157835 0.13069737 0.25095642]], shape=(5, 4), dtype=float32)


In [26]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([3,3])
  b = tf.random.uniform(tensor.shape)
  return a, b

@tf.function
def g():
  a = tf.random.uniform([3, 3])
  b = tf.random.uniform(tensor.shape)
  return a, b

print(f())    # prints "(A1, A2)"
print(g())    # prints "(A1, A2)"

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.13047123, 0.9760946 , 0.01222026],
       [0.5802934 , 0.8661562 , 0.48496962],
       [0.308123  , 0.9911289 , 0.57644176]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.1689806 , 0.9725481 , 0.90036285, 0.16582811],
       [0.1454581 , 0.48029935, 0.02495587, 0.99239147],
       [0.02835405, 0.10649502, 0.45283175, 0.87260246],
       [0.6877538 , 0.24809706, 0.95886254, 0.24039495],
       [0.65701306, 0.21762824, 0.8495487 , 0.19223797]], dtype=float32)>)
(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.13047123, 0.9760946 , 0.01222026],
       [0.5802934 , 0.8661562 , 0.48496962],
       [0.308123  , 0.9911289 , 0.57644176]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.1689806 , 0.9725481 , 0.90036285, 0.16582811],
       [0.1454581 , 0.48029935, 0.02495587, 0.99239147],
       [0.02835405, 0.10649502, 0.45283175, 0.87260246],
       [0.6877538 , 0.2480

In [27]:
# From tensorflow website:

tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


### If the operation seed is set but not the global seed:

In [28]:
# we get different results for every call to the random op, but the same sequence for every re-run of the program:

print(tf.random.uniform([3], seed=1))
print(tf.random.uniform(tensor.shape, seed=1))

tf.Tensor([0.1689806  0.9725481  0.90036285], shape=(3,), dtype=float32)
tf.Tensor(
[[0.92531705 0.29733074 0.11319971 0.98067176]
 [0.9943923  0.02966309 0.17640233 0.6509999 ]
 [0.42683613 0.20697045 0.640645   0.95358   ]
 [0.598192   0.9752364  0.5916792  0.60205007]
 [0.36065137 0.8292481  0.5240288  0.098611  ]], shape=(5, 4), dtype=float32)


In [29]:
# From tensorflow website

print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.09701788], shape=(1,), dtype=float32)
tf.Tensor([0.23129189], shape=(1,), dtype=float32)


### When both the operation seed, and global seed are set:

In [30]:
# the same sequence for every re-run of the program:

tf.random.set_seed(64)
print(tf.random.uniform([3], seed=2))
print(tf.random.uniform(tensor.shape, seed=5))
tf.random.set_seed(64)
print(tf.random.uniform([3], seed=2))
print(tf.random.uniform(tensor.shape, seed=5))

tf.Tensor([0.40422785 0.36240613 0.09227574], shape=(3,), dtype=float32)
tf.Tensor(
[[0.63136184 0.68330085 0.50041425 0.9098047 ]
 [0.27383792 0.3910135  0.00739944 0.78876984]
 [0.54777634 0.31669033 0.84119165 0.13814104]
 [0.50102234 0.33068907 0.6196461  0.19769883]
 [0.87463033 0.7988496  0.0536865  0.7549015 ]], shape=(5, 4), dtype=float32)
tf.Tensor([0.40422785 0.36240613 0.09227574], shape=(3,), dtype=float32)
tf.Tensor(
[[0.63136184 0.68330085 0.50041425 0.9098047 ]
 [0.27383792 0.3910135  0.00739944 0.78876984]
 [0.54777634 0.31669033 0.84119165 0.13814104]
 [0.50102234 0.33068907 0.6196461  0.19769883]
 [0.87463033 0.7988496  0.0536865  0.7549015 ]], shape=(5, 4), dtype=float32)


In [31]:
# From tensorflow website:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [32]:
@tf.function
def foo():
  a = tf.random.uniform([3, 2], seed=3)
  b = tf.random.uniform(tensor.shape, seed=5)
  return a, b
print(foo())
print(foo())

@tf.function
def bar():
  a = tf.random.uniform([2, 3])
  b = tf.random.uniform(tensor.shape)
  return a, b
print(bar())
print(bar())

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.96046877, 0.5811516 ],
       [0.64159   , 0.96217656],
       [0.05434954, 0.41893446]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.5191684 , 0.25865102, 0.30959463, 0.16933537],
       [0.7262864 , 0.5062971 , 0.93143713, 0.5186522 ],
       [0.32608354, 0.11557162, 0.11819661, 0.81512475],
       [0.2236216 , 0.37421417, 0.320786  , 0.05357528],
       [0.24286973, 0.16004622, 0.5363531 , 0.81584346]], dtype=float32)>)
(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.05653167, 0.46063077],
       [0.5289451 , 0.72455823],
       [0.7737336 , 0.57899153]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.86767614, 0.35417783, 0.42725182, 0.37610912],
       [0.14602256, 0.11361539, 0.71319044, 0.8048644 ],
       [0.50970125, 0.14274323, 0.8574256 , 0.07337177],
       [0.6025082 , 0.29182398, 0.3373251 , 0.00705373],
       [0.9833559 , 0.9090518 , 0.1808362

In [33]:
# From tensorflow website:

@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


# Exercise completed. Starting a new session:
* It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:
>Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


In [34]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [35]:
# Create a tensor of all ones
tf.ones([5, 5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [36]:
# Create a tensor of all zeros
print(tf.zeros([5, 5]))
print(tf.zeros(shape=(3, 4)))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [37]:
# We can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector)      # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [38]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A) #original shape
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [39]:
A.ndim

3

## Getting information from tensors
When delaling with tensors you problably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [40]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [41]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [42]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [43]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing tensors
* Tensors can be indexed just like Python lists

In [44]:
# In Python how we get the first 2 elements
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [45]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [46]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [47]:
rank_4_tensor[:1, :, :, :1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [48]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [49]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [50]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [51]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [52]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [53]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [54]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #"-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [55]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the first 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [56]:
# Expand the middle axis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [57]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic operations**
  
+, - , * , /

In [58]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [59]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [60]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [61]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [62]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [63]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

# **Matrix Multiplication**

In machine learning, Matrix multiplication is one of the most common tensor operations

In [64]:
# Matrix Multiplication in tersorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [65]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [66]:
# It is not same as matrix multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [67]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

## Try to matrix multiply tensors of same shape
### tf.matmul(X, Y)
### Error!
* Here how to do it.

In [68]:
# Lets's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [69]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [70]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [71]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [72]:
# Try to change the shape of X instead of Y:
tf.reshape(X, shape=(2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [73]:
# Try to matrix multiply reshaped X by Y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [74]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [75]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also referred to as the dot product.

We can perform matrix  multiplication using:
* tf.matmul()
* tv.tensordot()

In [76]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [77]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [78]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [79]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [80]:
# check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [81]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, we will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules.

### Changing the datatype of a tensor

In [82]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [83]:
C = tf.constant([7, 4])
C.dtype

tf.int32

In [84]:
# Change from float32 to float16 (reduce precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [85]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 4.], dtype=float32)>,
 tf.float32)

In [86]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([7., 4.], dtype=float16)>

### Aggregating tensors

**Aggregating tensors** = condensing them from multiple values down to a smaller amount of values

In [87]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [88]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [89]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([12, 35, 71, 59, 26, 17, 54, 23, 50, 57, 48, 20, 95, 77,  7,  7, 52,
       52, 44, 62, 97, 69, 62, 16, 89, 56, 35, 16, 70, 47, 28, 79,  6, 57,
       92, 31, 35, 45, 44, 62, 45, 96, 65,  2,  5, 64,  6, 75, 25,  0])>

In [90]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [91]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [92]:
np.min(E)

np.int64(0)

In [93]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [94]:
np.max(E)

np.int64(97)

In [95]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [96]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2287>

⚒ **Exercise:** Find the variance and standard deviation of tensor "E".


In [97]:
# Find the variance: variance is a measure of how the data is spread or dispersed around the mean.
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=738.912353515625>

### Or we can use tensorflow_probability as tfp
* To find the variance of our tensor, we need access to tensorflow_probability

In [98]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=739>

In [99]:
# Find the standard deviation: SD is a statistical measure of how data points vary from the mean.
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.182941436767578>

## Find the positional maximum and minimum

In [100]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [101]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [102]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [103]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [104]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [105]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [106]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

## **⚒ Practice Code**

In [107]:
# Create a new tensor
tf.random.set_seed(98)
Z = tf.random.uniform(shape=[100])
Z

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.79754066, 0.7440256 , 0.5025058 , 0.11604428, 0.59292793,
       0.2553811 , 0.637105  , 0.46234357, 0.5369334 , 0.4494865 ,
       0.5504985 , 0.09730339, 0.50553584, 0.04388678, 0.9968538 ,
       0.48595953, 0.47719407, 0.03320491, 0.5330105 , 0.68498814,
       0.04325283, 0.8111725 , 0.59306204, 0.10485494, 0.791716  ,
       0.15131462, 0.9883611 , 0.15995395, 0.18266046, 0.78677094,
       0.9114609 , 0.45847106, 0.65177655, 0.9922012 , 0.51506937,
       0.82666993, 0.24355614, 0.39952993, 0.06829011, 0.16215026,
       0.21207607, 0.7654183 , 0.17919922, 0.46541345, 0.07947206,
       0.562726  , 0.7007407 , 0.29473102, 0.9619025 , 0.00716686,
       0.32229877, 0.47122943, 0.89042103, 0.2836584 , 0.445516  ,
       0.42335117, 0.05672061, 0.5334716 , 0.7170973 , 0.45913208,
       0.11338484, 0.52929664, 0.23157775, 0.42309642, 0.20107841,
       0.23780811, 0.36459887, 0.49483788, 0.45785546, 0.14809024,
       0.59878

In [108]:
tf.size(Z), Z.shape, Z.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=100>, TensorShape([100]), 1)

* **tf.reduce_min(E)**
* **np.min(E)**
* **tf.reduce_max(E)**
* **np.max(E)**
* **tf.reduce_mean(E)**
* **tf.reduce_sum(E)**
* **tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))**
* **import tensorflow_probability as tfp** || **tfp.stats.variance(E)**
* **tf.math.reduce_std(tf.cast(E, dtype=tf.float32))**
* Find the positional maximum    **tf.argmax(F)**
* Index on our largest value position   **F[tf.argmax(F)]**
* Find the max value of F    **tf.reduce_max(F)**
* Check for equality    **F[tf.argmax(F)] == tf.reduce_max(F)**
* Find the positional minimum    **tf.argmin(F)**
* Find the minimum using the positional minimum index    **F[tf.argmin(F)]**


In [109]:
# Find the minimum
tf.reduce_min(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.007166862487792969>

In [110]:
# Find the minimum in NumPy
np.min(Z)

np.float32(0.0071668625)

In [111]:
# Find the maximum
tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9968538284301758>

In [112]:
# Find the maximum in NumPy
np.max(Z)

np.float32(0.9968538)

In [113]:
# Finding mean
tf.reduce_mean(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.49799293279647827>

In [114]:
# Finding sum
tf.reduce_sum(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=49.799293518066406>

In [115]:
# Finding variance
tf.math.reduce_variance(tf.cast(Z, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.08307211846113205>

In [116]:
# Another way to find variance
import tensorflow_probability as tfp
tfp.stats.variance(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.08307211846113205>

In [117]:
# Finding standard deviation (SD)
tf.math.reduce_std(tf.cast(Z, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2882223427295685>

In [118]:
# Find the positional maximum
tf.argmax(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [119]:
# Index of the largest value position || Find the maximum using the positional maximum index
Z[tf.argmax(Z)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9968538284301758>

In [120]:
# Finding the max value of F
tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9968538284301758>

In [121]:
Z[tf.argmax(Z)] == tf.reduce_max(Z)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [122]:
# Find the positional minimum
tf.argmin(Z)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [123]:
# Find the minimum using the positional minimum index
Z[tf.argmin(Z)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.007166862487792969>

## **End of the Practice**

### Squeezing a tensor (removing all single dimensions)

In [124]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [125]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [126]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding
* One-hot encoding is a technique used to convert categorical data into a numerical format that can be used by machine learning algorithms.
* This method is particularly useful when dealing with categorical variables that do not have an inherent order or ranking.

In [127]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [128]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'offline', b'offline', b'offline'],
       [b'offline', b"We're live!", b'offline', b'offline'],
       [b'offline', b'offline', b"We're live!", b'offline'],
       [b'offline', b'offline', b'offline', b"We're live!"]], dtype=object)>

### **Exercise:** One-hot encoding.

In [129]:
# Create a list of indices
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth) # output: [3x3]

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [130]:
indices_2 = [0, 2, -1, 1]
depth_2 = 3
tf.one_hot(indices_2, depth_2, on_value=5.0, off_value=0.0) # output: [4x3]

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[5., 0., 0.],
       [0., 0., 5.],
       [0., 0., 0.],
       [0., 5., 0.]], dtype=float32)>

In [131]:
# Same code but different depth
indices_3 = [0, 2, -1, 1]
depth_3 = 4
tf.one_hot(indices_3, depth_3, on_value=7.0, off_value=0.0) # prediction:: output: [4x4]

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[7., 0., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 0.],
       [0., 7., 0., 0.]], dtype=float32)>

In [132]:
indices_4 = [[0, 2], [1, -1]]
depth_4 = 3
tf.one_hot(indices_4, depth_4, on_value=1.0, off_value=0.0, axis=-1) # output: [2x2x3]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 0., 1.]],

       [[0., 1., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [133]:
indices_5 = tf.ragged.constant([[0, 1], [2]])
print(indices_5)
depth_5 = 3
output = tf.one_hot(indices_5, depth_5, on_value=1.0, off_value=0.0) # output: [2 x None x 3]
print(output)

<tf.RaggedTensor [[0, 1], [2]]>
<tf.RaggedTensor [[[1.0, 0.0, 0.0],
  [0.0, 1.0, 0.0]], [[0.0, 0.0, 1.0]]]>


### In TensorFlow, a **tf.ragged.constant()** function for **tf.RaggedTensor** is used to represent tensors with variable-length dimensions. This is particularly useful when dealing with sequences of varying lengths, such as sentences in natural language processing.
* Example:
* The first row has 3 elements: [1, 2, 3]
* The second row has 2 elements: [4, 5]
* The third row is empty: []
* The fourth row has 4 elements: [6, 7, 8, 9]
* This allow us to handle data with varying lengths efficiently.

In [138]:
# In this code we implemented the same indices without tf.ragged.constant()
try:
  indices_6 = [[0, 1], [2]]
  print(indices_6)
  depth_6 = 3
  output = tf.one_hot(indices_6, depth_6, on_value=1.0, off_value=0.0)
  print(output)
except:
  print("ERROR! - Can't convert non-rectangular Python sequence to Tensor.\nPlease follow the previous example.")

[[0, 1], [2]]
ERROR! - Can't convert non-rectangular Python sequence to Tensor.
Please follow the previous example.


### **Exercise End.**