<a href="https://colab.research.google.com/github/masrik-dev/Deep-Learning-with-TensorFlow-and-Python/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try

# Introduction to Tensors

In [43]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [44]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [45]:
# Check the number or dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [46]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [47]:
# Check the dimension of our vector
vector.ndim

1

In [48]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [49]:
matrix.ndim

2

In [50]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) #specify the data type with dtype parameter.
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [51]:
# What's the number dimensions of another)matrix?
another_matrix.ndim

2

In [52]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [53]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


# Creating tensors with tf.Variable

In [54]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [55]:
# Let's try change one of the elements in our chagneable tensor
#changeable_tensor[0] = 7
#changeable_tensor

In [56]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [57]:
# Let's try change our unchangeable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [58]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [59]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

In [60]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [61]:
# Shuffle our not_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Exercise: Generate random tensor, and shuffle it. Then test the global and local seed code.

In [62]:
# Step 1: Create random tensor:
random_tensor = tf.random.Generator.from_seed(32)
random_tensor = random_tensor.normal(shape=(5, 4))
random_tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.2364518 ],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265],
       [-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174],
       [ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
       [-0.645002  ,  0.18022095, -0.14656258,  0.34374258]],
      dtype=float32)>

In [63]:
random_tensor.ndim

2

In [64]:
# Step 2: Shuffle the random_tensor.
shuffle_tensor = tf.random.shuffle(random_tensor)
shuffle_tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
       [-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265],
       [ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.2364518 ],
       [-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174]],
      dtype=float32)>

In [65]:
tensor = tf.constant(shuffle_tensor)
tensor

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.495291  , -0.648484  , -1.8700892 ,  2.7830641 ],
       [-0.645002  ,  0.18022095, -0.14656258,  0.34374258],
       [-0.1589871 ,  1.302304  ,  0.9592239 ,  0.85874265],
       [ 0.7901182 ,  1.585549  ,  0.4356279 ,  0.2364518 ],
       [-1.5181769 ,  1.4020647 ,  1.5570306 , -0.96762174]],
      dtype=float32)>

### If neither the global seed nor the operation seed is set:

In [66]:
# we get different results for every call to the random op and every re-run of the program:

print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform(tensor.shape))  # generates 'A2'

tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor(
[[0.7402308  0.33938193 0.5692506  0.44811392]
 [0.29285502 0.4260056  0.62890387 0.691061  ]
 [0.30925727 0.89236605 0.66396606 0.30541587]
 [0.8724164  0.1025728  0.56819403 0.25427842]
 [0.7253866  0.4770788  0.46289814 0.88944995]], shape=(5, 4), dtype=float32)


### If the global seed is set but the operation seed is not set:


In [67]:
# we get different results for every call to the random op, but the same sequence for every re-run of the program:

tf.random.set_seed(64)
print(tf.random.uniform([3]))             # generates 'A1'
print(tf.random.uniform(tensor.shape))    # generates 'A2'


tf.Tensor([0.41049755 0.47658968 0.46416903], shape=(3,), dtype=float32)
tf.Tensor(
[[0.04468966 0.6561477  0.33908975 0.823082  ]
 [0.3915465  0.05389285 0.9497212  0.7511488 ]
 [0.29618108 0.11224461 0.5920911  0.6658716 ]
 [0.72812736 0.5153334  0.7647536  0.57969654]
 [0.740461   0.86157835 0.13069737 0.25095642]], shape=(5, 4), dtype=float32)


In [68]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([3,3])
  b = tf.random.uniform(tensor.shape)
  return a, b

@tf.function
def g():
  a = tf.random.uniform([3, 3])
  b = tf.random.uniform(tensor.shape)
  return a, b

print(f())    # prints "(A1, A2)"
print(g())    # prints "(A1, A2)"

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.13047123, 0.9760946 , 0.01222026],
       [0.5802934 , 0.8661562 , 0.48496962],
       [0.308123  , 0.9911289 , 0.57644176]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.1689806 , 0.9725481 , 0.90036285, 0.16582811],
       [0.1454581 , 0.48029935, 0.02495587, 0.99239147],
       [0.02835405, 0.10649502, 0.45283175, 0.87260246],
       [0.6877538 , 0.24809706, 0.95886254, 0.24039495],
       [0.65701306, 0.21762824, 0.8495487 , 0.19223797]], dtype=float32)>)
(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.13047123, 0.9760946 , 0.01222026],
       [0.5802934 , 0.8661562 , 0.48496962],
       [0.308123  , 0.9911289 , 0.57644176]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.1689806 , 0.9725481 , 0.90036285, 0.16582811],
       [0.1454581 , 0.48029935, 0.02495587, 0.99239147],
       [0.02835405, 0.10649502, 0.45283175, 0.87260246],
       [0.6877538 , 0.2480

In [69]:
# From tensorflow website:

tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


### If the operation seed is set but not the global seed:

In [70]:
# we get different results for every call to the random op, but the same sequence for every re-run of the program:

print(tf.random.uniform([3], seed=1))
print(tf.random.uniform(tensor.shape, seed=1))

tf.Tensor([0.1689806  0.9725481  0.90036285], shape=(3,), dtype=float32)
tf.Tensor(
[[0.92531705 0.29733074 0.11319971 0.98067176]
 [0.9943923  0.02966309 0.17640233 0.6509999 ]
 [0.42683613 0.20697045 0.640645   0.95358   ]
 [0.598192   0.9752364  0.5916792  0.60205007]
 [0.36065137 0.8292481  0.5240288  0.098611  ]], shape=(5, 4), dtype=float32)


In [71]:
# From tensorflow website

print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.09701788], shape=(1,), dtype=float32)
tf.Tensor([0.23129189], shape=(1,), dtype=float32)


### When both the operation seed, and global seed are set:

In [72]:
# the same sequence for every re-run of the program:

tf.random.set_seed(64)
print(tf.random.uniform([3], seed=2))
print(tf.random.uniform(tensor.shape, seed=5))
tf.random.set_seed(64)
print(tf.random.uniform([3], seed=2))
print(tf.random.uniform(tensor.shape, seed=5))

tf.Tensor([0.40422785 0.36240613 0.09227574], shape=(3,), dtype=float32)
tf.Tensor(
[[0.63136184 0.68330085 0.50041425 0.9098047 ]
 [0.27383792 0.3910135  0.00739944 0.78876984]
 [0.54777634 0.31669033 0.84119165 0.13814104]
 [0.50102234 0.33068907 0.6196461  0.19769883]
 [0.87463033 0.7988496  0.0536865  0.7549015 ]], shape=(5, 4), dtype=float32)
tf.Tensor([0.40422785 0.36240613 0.09227574], shape=(3,), dtype=float32)
tf.Tensor(
[[0.63136184 0.68330085 0.50041425 0.9098047 ]
 [0.27383792 0.3910135  0.00739944 0.78876984]
 [0.54777634 0.31669033 0.84119165 0.13814104]
 [0.50102234 0.33068907 0.6196461  0.19769883]
 [0.87463033 0.7988496  0.0536865  0.7549015 ]], shape=(5, 4), dtype=float32)


In [73]:
# From tensorflow website:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [74]:
@tf.function
def foo():
  a = tf.random.uniform([3, 2], seed=3)
  b = tf.random.uniform(tensor.shape, seed=5)
  return a, b
print(foo())
print(foo())

@tf.function
def bar():
  a = tf.random.uniform([2, 3])
  b = tf.random.uniform(tensor.shape)
  return a, b
print(bar())
print(bar())

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.96046877, 0.5811516 ],
       [0.64159   , 0.96217656],
       [0.05434954, 0.41893446]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.5191684 , 0.25865102, 0.30959463, 0.16933537],
       [0.7262864 , 0.5062971 , 0.93143713, 0.5186522 ],
       [0.32608354, 0.11557162, 0.11819661, 0.81512475],
       [0.2236216 , 0.37421417, 0.320786  , 0.05357528],
       [0.24286973, 0.16004622, 0.5363531 , 0.81584346]], dtype=float32)>)
(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.05653167, 0.46063077],
       [0.5289451 , 0.72455823],
       [0.7737336 , 0.57899153]], dtype=float32)>, <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.86767614, 0.35417783, 0.42725182, 0.37610912],
       [0.14602256, 0.11361539, 0.71319044, 0.8048644 ],
       [0.50970125, 0.14274323, 0.8574256 , 0.07337177],
       [0.6025082 , 0.29182398, 0.3373251 , 0.00705373],
       [0.9833559 , 0.9090518 , 0.1808362

In [75]:
# From tensorflow website:

@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


# Exercise completed. Starting a new session:
* It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:
>Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


In [76]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [77]:
# Create a tensor of all ones
tf.ones([5, 5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [78]:
# Create a tensor of all zeros
print(tf.zeros([5, 5]))
print(tf.zeros(shape=(3, 4)))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [79]:
# We can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector)      # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [80]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A) #original shape
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [81]:
A.ndim

3

## Getting information from tensors
When delaling with tensors you problably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [82]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [83]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [84]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [87]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


### Indexing tensors
* Tensors can be indexed just like Python lists

In [88]:
# In Python how we get the first 2 elements
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [89]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [90]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [91]:
rank_4_tensor[:1, :, :, :1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [92]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [93]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [94]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [95]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [96]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [97]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [98]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #"-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [99]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the first 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [100]:
# Expand the middle axis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [101]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic operations**
  
+, - , * , /

In [103]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [104]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [105]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [106]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [107]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [108]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In machine learning, Matrix multiplication is one of the most common tensor operations

In [111]:
# Matrix Multiplication in tersorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [112]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [113]:
# It is not same as matrix multiplication
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [114]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [116]:
# Try to matrix multiply tensors of same shape
#tf.matmul(X, Y)